# Generated by Django 3.2.25 on 2025-11-17 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('arriving', 'Driver Arriving'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('passenger_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to=settings.AUTH_USER_MODEL)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_lat', models.FloatField(default=0)),
                ('driver_lng', models.FloatField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='rides.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='RideFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.FloatField(default=50)),
                ('distance_km', models.FloatField(default=0)),
                ('time_minutes', models.FloatField(default=0)),
                ('total_fare', models.FloatField(default=0)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fare', to='rides.riderequest')),
            ],
        ),
    ]
