# Generated by Django 3.2.25 on 2025-11-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='drop_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pickup_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='ride_type',
            field=models.CharField(default='car', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='driver_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='passenger_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
