# Generated by Django 3.2.25 on 2025-12-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_auto_20251130_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='drop_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='pickup_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='ride_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
