# Generated by Django 3.2.25 on 2025-12-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_auto_20251201_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
